### ISSUE TITLE
rocketmq5.2，用的是支持5.2的dashboard，无法新增Topic，命令新增Topic后console查询不到，console topic页面报错Source must not be null

### ISSUE THREAD

**Issue by qw2575166772** [apache/rocketmq-dashboard#216]
rocketmq5.2，用的是支持5.2的dashboard，无法新增Topic，命令新增Topic后console查询不到，console topic页面报错Source must not be null。其他消费者生产者 查询收到的消息暂时正常
 
![1719999845341](https://github.com/apache/rocketmq-dashboard/assets/51700329/2737c7ed-f2f4-433b-9dee-7f25955f1022)

**Comment by onejimmyboy** [comment]
是不是dashboard没有连接上broker？看一下集群Cluster页签

**Comment by onejimmyboy** [comment]
还有一个，通过后台新增的topic，前端确实看不到，f12看后端接口返回的话能看到新增的topic。这个是个bug

**Comment by qw2575166772** [comment]
<img width="960" alt="1d4b0f08a4f2783402872dc9e945f2f" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/9434602c-9f41-4ff9-855d-ae2d365ff10c">
<img width="960" alt="31a15ece6df342ebbad859fb21f20d0" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/f52ba3d2-e9c6-4c64-b20d-690eff1c8083">
<img width="950" alt="837e7d2737666b947ad372172510f9c" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/d176c949-9983-40ea-a8b1-a129788f84fd">
<img width="956" alt="3428358c920bf6b36ca578cb70d5acb" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/32db56d7-d791-4820-af32-423c6a9fbdc3">
<img width="960" alt="ae074cf60ccadd77663e1deead653e1" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/12a96276-76eb-4ae6-86a8-50ca936c0b35">
<img width="956" alt="bfd6a7c5ef618f338aff735a5cf2424" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/00d06e7b-7d98-42c2-b156-35eedde462a3">
<img width="946" alt="d67a1015293794aad4354a909958383" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/677e4d26-42ba-461e-a29d-92697c6527cf">
老师们，正常连接mq集群，无论页面创建Topic还是后台创建，都无法显示，程序用着MQ正常。

**Comment by qw2575166772** [comment]
<img width="960" alt="31a15ece6df342ebbad859fb21f20d0" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/d8afd33b-c99c-45e1-bb9e-83a1c956601e">
<img width="477" alt="447baa3402064c0e4d259924a4a1b4a" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/84f56135-4fdc-458c-adad-83fd5ee4c4a3">
<img width="950" alt="837e7d2737666b947ad372172510f9c" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/ed248f7b-fcbe-4ae9-b0eb-1d5169d7268f">
<img width="956" alt="3428358c920bf6b36ca578cb70d5acb" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/b3576ac3-88f0-418d-bdc3-724400669c87">
![1720074023386](https://github.com/apache/rocketmq-dashboard/assets/51700329/0ece202a-bf5b-4a89-95e8-dbe80fb18d53)
<img width="956" alt="bfd6a7c5ef618f338aff735a5cf2424" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/c788f59f-56df-401e-b37c-7166210dc682">
<img width="946" alt="d67a1015293794aad4354a909958383" src="https://github.com/apache/rocketmq-dashboard/assets/51700329/208dc915-3d89-4d67-9afa-618ae9d99bf7">
正常连接mq，mq被程序连也可以正常消费使用，但是到topic这个页面就报错Source must not be null ,不显示

**Comment by qw2575166772** [comment]
> 还有一个，通过后台新增的topic，前端确实看不到，f12看后端接口返回的话能看到新增的topic。这个是个bug

老师 是正常连接broker的，我下面放了图，有什么解决办法吗

**Comment by onejimmyboy** [comment]
这个得看有一下rocketmq-dashboard的日志吧，看详细报了什么错

**Comment by 1294566108** [comment]
@qw2575166772 麻烦提供一下新增topic失败使用的命令，以及查询topic请求的F12返回信息

**Comment by seart** [comment]
我也遇到了同样的问

<img width="1573" alt="image" src="https://github.com/user-attachments/assets/6354e4f1-47b8-4ecd-8858-bab289143770">


2024-07-23 11:13:04 [2024-07-23 03:13:04.044] ERROR http-nio-8080-exec-5 - op=global_exception_handler_print_error
2024-07-23 11:13:04 java.lang.IllegalArgumentException: Source must not be null
2024-07-23 11:13:04 at org.springframework.util.Assert.notNull(Assert.java:201)
2024-07-23 11:13:04 at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:757)
2024-07-23 11:13:04 at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:701)
2024-07-23 11:13:04 at org.apache.rocketmq.dashboard.service.impl.TopicServiceImpl.examineTopicConfig(TopicServiceImpl.java:211)
2024-07-23 11:13:04 at org.apache.rocketmq.dashboard.service.impl.TopicServiceImpl.checkTopicType(TopicServiceImpl.java:132)
2024-07-23 11:13:04 at org.apache.rocketmq.dashboard.service.impl.TopicServiceImpl.examineAllTopicType(TopicServiceImpl.java:112)
2024-07-23 11:13:04 at org.apache.rocketmq.dashboard.controller.TopicController.listTopicType(TopicController.java:62)
2024-07-23 11:13:04 at org.apache.rocketmq.dashboard.controller.TopicController$$FastClassBySpringCGLIB$$8429e433.invoke(<generated>)
2024-07-23 11:13:04 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
2024-07-23 11:13:04 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
2024-07-23 11:13:04 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
2024-07-23 11:13:04 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
2024-07-23 11:13:04 at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
2024-07-23 11:13:04 at org.apache.rocketmq.dashboard.permisssion.PermissionAspect.checkPermission(PermissionAspect.java:67)
2024-07-23 11:13:04 at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
2024-07-23 11:13:04 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-23 11:13:04 at java.lang.reflect.Method.invoke(Method.java:498)
2024-07-23 11:13:04 at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
2024-07-23 11:13:04 at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
2024-07-23 11:13:04 at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
2024-07-23 11:13:04 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
2024-07-23 11:13:04 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
2024-07-23 11:13:04 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
2024-07-23 11:13:04 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
2024-07-23 11:13:04 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
2024-07-23 11:13:04 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
2024-07-23 11:13:04 at org.apache.rocketmq.dashboard.controller.TopicController$$EnhancerBySpringCGLIB$$e1b1c3d7.listTopicType(<generated>)
2024-07-23 11:13:04 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-23 11:13:04 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-07-23 11:13:04 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-23 11:13:04 at java.lang.reflect.Method.invoke(Method.java:498)
2024-07-23 11:13:04 at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
2024-07-23 11:13:04 at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
2024-07-23 11:13:04 at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
2024-07-23 11:13:04 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
2024-07-23 11:13:04 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
2024-07-23 11:13:04 at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
2024-07-23 11:13:04 at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
2024-07-23 11:13:04 at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
2024-07-23 11:13:04 at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
2024-07-23 11:13:04 at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
2024-07-23 11:13:04 at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
2024-07-23 11:13:04 at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
2024-07-23 11:13:04 at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-23 11:13:04 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-23 11:13:04 at org.apache.rocketmq.dashboard.filter.HttpBasicAuthorizedFilter.doFilter(HttpBasicAuthorizedFilter.java:45)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-23 11:13:04 at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
2024-07-23 11:13:04 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-23 11:13:04 at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
2024-07-23 11:13:04 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-23 11:13:04 at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
2024-07-23 11:13:04 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-23 11:13:04 at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
2024-07-23 11:13:04 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2024-07-23 11:13:04 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-23 11:13:04 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
2024-07-23 11:13:04 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
2024-07-23 11:13:04 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
2024-07-23 11:13:04 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
2024-07-23 11:13:04 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
2024-07-23 11:13:04 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
2024-07-23 11:13:04 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
2024-07-23 11:13:04 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
2024-07-23 11:13:04 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
2024-07-23 11:13:04 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
2024-07-23 11:13:04 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
2024-07-23 11:13:04 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2024-07-23 11:13:04 at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
2024-07-23 11:13:04 at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
2024-07-23 11:13:04 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2024-07-23 11:13:04 at java.lang.Thread.run(Thread.java:750)
2024-07-23 11:13:30 [2024-07-23 03:13:30.011] WARN collectTopicThread_2 - Exception caught: mqAdminExt get broker stats data TOPIC_PUT_NUMS failed, topic [TestTopic123]

**Comment by 1294566108** [comment]
@seart @qw2575166772 如果使用v5版本的话，需要检查一下新增topic的指令，是否有提前指定消息类型，未指定消息类型会默认UNSPECIFIED类。
具体命令可参考：sh ./mqadmin updateTopic -n <nameserver_address> -t <topic_name> -c DefaultCluster -a +message.type=NORMAL
