### ISSUE TITLE
只能查出普通topic，其他比如顺序topic显示不出来

### ISSUE THREAD

**Issue by jevonsnotes** [apache/rocketmq-dashboard#217]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
最近在尝试使用rocketmq，按照文档进行创建后
```
[root@gd4400-tst-tyzj-kylin-ecs-0019 bin]# ./mqadmin updateTopic -n 10.26.22.29:9876 -c DefaultCluster -t TOPIC_FIFO  -o true -a +message.type=FIFO
create topic to 10.26.22.29:10911 success.
set cluster orderConf. isOrder=true, orderConf=[broker-a:8]
TopicConfig [topicName=TOPIC_FIFO, readQueueNums=8, writeQueueNums=8, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=true, attributes={+message.type=FIFO}]
```
使用rocketmq spring发送消息报错
```
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 13  DESC: TopicMessageType validate failed, the expected type is FIFO, but actual type is NORMAL BROKER: 10.26.22.29:8080
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:774)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:610)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:592)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:536)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:1016)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1309)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1275)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:669)
	at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSendOrderly(RocketMQTemplate.java:769)
	at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSendOrderly(RocketMQTemplate.java:745)
	at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSendOrderly(RocketMQTemplate.java:732)
	at picc.spring.rocketmq.helper.RocketMqHelper.syncSendOrderly(RocketMqHelper.java:123)
	at picc.spring.test.server.api.RocketMqApi.lambda$testTopicFIFO$1(RocketMqApi.java:71)
	at picc.spring.test.server.api.RocketMqApi.looper(RocketMqApi.java:82)
	at picc.spring.test.server.api.RocketMqApi.testTopicFIFO(RocketMqApi.java:71)
	at picc.spring.test.server.api.RocketMqApi.test(RocketMqApi.java:40)
	at picc.spring.test.server.api.RocketMqApi$$FastClassBySpringCGLIB$$e0139f33.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```
- What did you expect to see?
查出所有用户创建的topic，并且显示topic实际类型。或者可能是我不熟悉，请教下怎么查勘topic类型，因为我翻遍了控制台都找不到。
- What did you see instead?
![image](https://github.com/apache/rocketmq-dashboard/assets/24319663/5f5e9182-b85b-48ed-bcfd-95b2f4c38e1f)

2. Please tell us about your environment:
linux
rocketmq 5.2.0
rocketmq spring 2.3.0
rocketmq dashboard 1.0.1-snapshot (一开始用的是1.0.0，后来更新了一下)

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by Gonzo-Tan** [comment]
试一试最右侧切换到 5.x 版本
