### ISSUE TITLE
无法查看消费终端

### ISSUE THREAD

**Issue by jevonsnotes** [apache/rocketmq-dashboard#218]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
查看消费终端
- What did you expect to see?
显示消费终端信息
- What did you see instead?

![image](https://github.com/apache/rocketmq-dashboard/assets/24319663/5782dfce-af8e-492c-b54e-208eafc6626f)

```
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 206  DESC: the consumer group[TOPIC_NORMAL_CONSUMER_GROUP_01] not online BROKER: 10.26.22.29:10911
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getConsumerConnectionList(MQClientAPIImpl.java:1648)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineConsumerConnectionInfo(DefaultMQAdminExtImpl.java:642)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineConsumerConnectionInfo(DefaultMQAdminExt.java:334)
        at org.apache.rocketmq.dashboard.service.client.MQAdminExtImpl.examineConsumerConnectionInfo(MQAdminExtImpl.java:642)
        at org.apache.rocketmq.dashboard.service.client.MQAdminExtImpl$$FastClassBySpringCGLIB$$a15c4ca6.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at org.apache.rocketmq.dashboard.aspect.admin.MQAdminAspect.aroundMQAdminMethod(MQAdminAspect.java:52)
        at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
2. Please tell us about your environment:
linux
rocketmq 5.2.0
rocketmq spring 2.3.0
rocketmq dashboard 1.0.1-snapshot
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by jevonsnotes** [comment]
命令也无法查看
```
[root@gd4400-tst-tyzj-kylin-ecs-0019 bin]# ./mqadmin consumerStatus  -n 10.26.22.29:9876 -g TOPIC_NORMAL_CONSUMER_GROUP_01
org.apache.rocketmq.tools.command.SubCommandException: ConsumerStatusSubCommand command failed
        at org.apache.rocketmq.tools.command.consumer.ConsumerStatusSubCommand.execute(ConsumerStatusSubCommand.java:149)
        at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:164)
        at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:114)
Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: %RETRY%TOPIC_NORMAL_CONSUMER_GROUP_01
See https://rocketmq.apache.org/docs/bestPractice/06FAQ for further details.
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:2011)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1982)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineTopicRouteInfo(DefaultMQAdminExtImpl.java:583)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineConsumerConnectionInfo(DefaultMQAdminExtImpl.java:616)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineConsumerConnectionInfo(DefaultMQAdminExt.java:331)
        at org.apache.rocketmq.tools.command.consumer.ConsumerStatusSubCommand.execute(ConsumerStatusSubCommand.java:89)
```
一直报找不到retry路由，然后我又创建了一个  %RETRY%TOPIC_NORMAL_CONSUMER_GROUP_01 主题，再次查询后，提示

```
[root@gd4400-tst-tyzj-kylin-ecs-0019 bin]# ./mqadmin consumerStatus  -n 10.26.22.29:9876 -g TOPIC_NORMAL_CONSUMER_GROUP_01                                             
org.apache.rocketmq.tools.command.SubCommandException: ConsumerStatusSubCommand command failed
        at org.apache.rocketmq.tools.command.consumer.ConsumerStatusSubCommand.execute(ConsumerStatusSubCommand.java:149)
        at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:164)
        at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:114)
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 206  DESC: the consumer group[TOPIC_NORMAL_CONSUMER_GROUP_01] not online BROKER: 10.26.22.29:10911
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getConsumerConnectionList(MQClientAPIImpl.java:1776)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineConsumerConnectionInfo(DefaultMQAdminExtImpl.java:622)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineConsumerConnectionInfo(DefaultMQAdminExt.java:331)
        at org.apache.rocketmq.tools.command.consumer.ConsumerStatusSubCommand.execute(ConsumerStatusSubCommand.java:89)
        ... 2 more
```

**Comment by Gonzo-Tan** [comment]
这个是因为 5.x 之后 broker 里面没有 consumer 信息导致的，参考这个 pr :
https://github.com/apache/rocketmq-dashboard/pull/219

**Comment by onejimmyboy** [comment]
重试topic列表存在这个topic吗？TOPIC_NORMAL_CONSUMER_GROUP_01，没有的话可以创建一个试试

**Comment by jevonsnotes** [comment]
> 重试topic列表存在这个topic吗？TOPIC_NORMAL_CONSUMER_GROUP_01，没有的话可以创建一个试试

有的
![image](https://github.com/apache/rocketmq-dashboard/assets/24319663/9d07e4d0-58bb-4a00-86a9-2350ced9097e)

**Comment by ProfutW** [comment]
使用5.X gRPC SDK就会有这个问题，使用4.X Remoting SDK就没问题，应该是adminTool没有从proxy拉数据

**Comment by jevonsnotes** [comment]
> 使用5.X gRPC SDK就会有这个问题，使用4.X Remoting SDK就没问题，应该是adminTool没有从proxy拉数据

我之前使用的是rocketmq spring的sdk，发送fifo会报错，才切换的v5 grpc sdk
https://github.com/apache/rocketmq-clients/discussions/785

**Comment by jevonsnotes** [comment]
更新代码后，将VIP配置调整为false可以解决
```
rocketmq:
  config:
    isVIPChannel: false
```

**Comment by Yelijah** [comment]
> 更新代码后，将VIP配置调整为false可以解决
> 
> ```
> rocketmq:
>   config:
>     isVIPChannel: false
> ```

proxy独立部署时还是有问题
